# Generated by Django 2.2 on 2019-08-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20190816_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='categorg',
            new_name='category',
        ),
    ]
